#!/usr/bin/env php
<?php
/******************************************************************************
 ******************************************************************************
 *   ##########  ##########  ##########  ##########  ####    ####  ##########
 *   ##      ##  ##      ##  ##          ##          ## ##  ## ##  ##      ##
 *   ##########  ##########  ##    ####  ##    ####  ##   ##   ##  ##########
 *   ##          ##    ##    ##########  ##########  ##        ##  ##    ##
 *******************************************************************************
 *******************************************************************************/

/**
 *  Copyright 2010 Nickolas Whiting
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *
 * @author  Nickolas Whiting  <me@nwhiting.com>
 * @package  Prggmr
 * @category  Web
 * @copyright  Copyright (c), 2010 Nickolas Whiting
 */

if ($_ENV['PWD'] !== null) {
   set_include_path($_ENV['PWD'] . PATH_SEPARATOR . get_include_path());
}

if (!file_exists($_ENV['PWD'].'/var/bootstrap.php')) {
    die ("Failed to locate prggmr $_ENV[PWD]/var/bootstrap.php file, check your bootstrap file in $_ENV[PWD]/var/bootstrap.php");
}

include $_ENV['PWD'].'/var/bootstrap.php';